[metadata]
name = "Level 3"
biome = "DAYLIGHT"
help_text = "←/→: Move Camera"

[[layers]]
pillars = true
height_map = """
11111111
..444144
..444414
...00004
"""
modifiers = ["""
P.......
........
........
...G....
"""]
