[metadata]
name = "Level 6"
biome = "DAYLIGHT"
help_text = "6"

[[layers]]
pillars = true
height_map = """
3333.3
......
"""
modifiers = ["""
PIII.G
......
""""]

[[layers]]
pillars = false
height_map = """
......
2.....
"""
modifiers = ["""
......
......
""""]
movement_maps = [
    [[-1, 0, 2], [1, 0, -2]]
]
