[metadata]
name = "Level 6"
biome = "DAYLIGHT"
help_text = "6"

[[layers]]
pillars = true
height_map = """
......
......
33..1.
21....
..1..1
.....1
"""
modifiers = ["""
......
......
P...G.
......
......
......
""""]

[[layers]]
pillars = false
height_map = """
......
......
..11..
......
......
......
"""
modifiers = ["""
......
......
..MM..
......
......
......
""""]
movement_maps = [
    [[-1, 0, 2], [1, 0, -2], [1, 0, -2], [-1, 0, 2]],
    [[1, 0, -2], [-1, 0, 2]],
]
