[metadata]
name = "Level 7"
biome = "DAYLIGHT"
help_text = "7"

[[layers]]
pillars = true
height_map = """
.........
..1..00..
.1....10.
....1..00
"""
modifiers = ["""
.........
.........
.P....G..
.........
""""]

[[layers]]
pillars = false
height_map = """
..1......
.........
..1.1....
......0..
"""
modifiers = ["""
..M......
.........
..M.M....
......M..
""""]
movement_maps = [
    [[2, 0, 0], [-2, 0, 0]],
    [[1, 0, -1], [-1, 0, 1]],
    [[-1, 0, 1], [1, 0, -1]],
    [[0, 1, 0], [0, -1, 0]],
]
