[metadata]
name = "Level 8"
biome = "DAYLIGHT"
help_text = "8"

[[layers]]
pillars = false
height_map = """
1111
"""
modifiers = ["""
P..G
"""", """
MMMM
"""]
movement_maps = [
    [[0, -1, 0], [0, 1, 0]],
    [[0, 1, 0], [0, -1, 0]],
    [[0, 4, 0], [0, 1, 0], [0, -4, 0], [0, -1, 0]],
    [[0, 4, 0], [0, 1, 0], [0, -5, 0]],
]
