[display]
width = 1280
height = 960

[display.water]
shadows_enabled = true

[display.sun]
initial_time_of_day = 0.45
seconds_per_day = 20
shadows_enabled = true
illuminance = 3000.0
illuminance_variation = 1000.0
